#!/usr/bin/env python3
"""Taxonomy tooling: validate JSON/CSV parity and generate the Markdown format.

Usage:
    python scripts/taxonomy_tools.py generate   # (re)write taxonomy.md and README term lists
    python scripts/taxonomy_tools.py check      # validate everything; exit 1 on any problem

Source of truth: taxonomy.json. taxonomy.csv and taxonomy.md are derived views
and must stay in sync (enforced by `check`, which runs in CI).
"""

import csv
import io
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = ROOT / "taxonomy.json"
CSV_PATH = ROOT / "taxonomy.csv"
MD_PATH = ROOT / "taxonomy.md"
README_PATH = ROOT / "README.md"

BEGIN_MARK = "<!-- BEGIN:CATEGORY-TERMS (generated by scripts/taxonomy_tools.py — do not edit by hand) -->"
END_MARK = "<!-- END:CATEGORY-TERMS -->"

REQUIRED_FIELDS = ("id", "term", "category", "definition", "related_terms")


def gfm_slug(text: str) -> str:
    """Approximate GitHub's Markdown heading anchor algorithm."""
    slug = text.strip().lower()
    slug = re.sub(r"[^\w\- ]", "", slug, flags=re.UNICODE)
    slug = slug.replace(" ", "-")
    return slug


def load_json():
    with JSON_PATH.open(encoding="utf-8") as fh:
        data = json.load(fh)
    return data["taxonomy"]


def load_csv():
    with CSV_PATH.open(encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh))


def render_markdown(tax) -> str:
    by_category = {c: [] for c in tax["categories"]}
    for term in tax["terms"]:
        by_category[term["category"]].append(term)
    id_to_term = {t["id"]: t["term"] for t in tax["terms"]}

    out = io.StringIO()
    out.write(f"# {tax['title']}\n\n")
    out.write(
        f"Version {tax['version']} — {tax['date']} — {tax['author']} — "
        f"License {tax['license']}\n\n"
    )
    out.write(
        "> Generated from [taxonomy.json](taxonomy.json) by "
        "`scripts/taxonomy_tools.py generate`. Do not edit this file by hand.\n\n"
    )
    out.write("## Contents\n\n")
    for i, cat in enumerate(tax["categories"], start=1):
        out.write(f"{i}. [{cat}](#{gfm_slug(cat)}) — {len(by_category[cat])} terms\n")
    out.write("\n---\n")

    for cat in tax["categories"]:
        out.write(f"\n## {cat}\n")
        for term in by_category[cat]:
            out.write(f"\n### {term['term']}\n\n")
            out.write(f"{term['definition']}\n")
            related = [
                f"[{id_to_term[rid]}](#{gfm_slug(id_to_term[rid])})"
                for rid in term["related_terms"]
                if rid in id_to_term
            ]
            if related:
                out.write(f"\n**Related terms:** {', '.join(related)}\n")
    return out.getvalue()


def render_readme_block(tax) -> str:
    by_category = {c: [] for c in tax["categories"]}
    for term in tax["terms"]:
        by_category[term["category"]].append(term)

    lines = [BEGIN_MARK, ""]
    for i, cat in enumerate(tax["categories"], start=1):
        lines.append(f"### {i}. {cat}")
        lines.append("")
        for term in by_category[cat]:
            lines.append(f"- [{term['term']}](taxonomy.md#{gfm_slug(term['term'])})")
        lines.append("")
    lines.append(END_MARK)
    return "\n".join(lines)


def splice_readme(readme_text: str, block: str) -> str:
    begin = readme_text.find(BEGIN_MARK)
    end = readme_text.find(END_MARK)
    if begin == -1 or end == -1:
        raise SystemExit(
            "README.md is missing the CATEGORY-TERMS markers; cannot splice."
        )
    return readme_text[:begin] + block + readme_text[end + len(END_MARK):]


def validate(tax, csv_rows) -> list:
    errors = []
    ids = set()
    categories = set(tax["categories"])

    for idx, term in enumerate(tax["terms"]):
        where = f"taxonomy.json terms[{idx}] ({term.get('id', '?')})"
        for field in REQUIRED_FIELDS:
            if field not in term or term[field] in ("", None):
                errors.append(f"{where}: missing or empty field '{field}'")
        tid = term.get("id")
        if tid in ids:
            errors.append(f"{where}: duplicate id")
        ids.add(tid)
        if term.get("category") not in categories:
            errors.append(f"{where}: unknown category '{term.get('category')}'")

    for idx, term in enumerate(tax["terms"]):
        for rid in term.get("related_terms", []):
            if rid not in ids:
                errors.append(
                    f"taxonomy.json terms[{idx}] ({term.get('id')}): "
                    f"related term '{rid}' does not exist"
                )

    # CSV parity: same ids, and matching term/category/definition/related_terms.
    csv_by_id = {}
    for row in csv_rows:
        rid = row.get("id")
        if rid in csv_by_id:
            errors.append(f"taxonomy.csv: duplicate id '{rid}'")
        csv_by_id[rid] = row

    json_by_id = {t["id"]: t for t in tax["terms"]}
    for missing in sorted(set(json_by_id) - set(csv_by_id)):
        errors.append(f"taxonomy.csv: id '{missing}' present in JSON but absent in CSV")
    for extra in sorted(set(csv_by_id) - set(json_by_id)):
        errors.append(f"taxonomy.csv: id '{extra}' present in CSV but absent in JSON")

    for tid in sorted(set(json_by_id) & set(csv_by_id)):
        jt, ct = json_by_id[tid], csv_by_id[tid]
        for field in ("term", "category", "definition"):
            if jt[field] != ct.get(field):
                errors.append(f"parity mismatch on '{tid}' field '{field}' (JSON != CSV)")
        json_related = ";".join(jt["related_terms"])
        if json_related != (ct.get("related_terms") or ""):
            errors.append(f"parity mismatch on '{tid}' field 'related_terms' (JSON != CSV)")

    return errors


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "check"
    tax = load_json()
    csv_rows = load_csv()

    errors = validate(tax, csv_rows)
    if errors:
        for err in errors:
            print(f"ERROR: {err}")
        sys.exit(1)

    md = render_markdown(tax)
    readme_new = splice_readme(
        README_PATH.read_text(encoding="utf-8"), render_readme_block(tax)
    )

    if mode == "generate":
        MD_PATH.write_text(md, encoding="utf-8", newline="\n")
        README_PATH.write_text(readme_new, encoding="utf-8", newline="\n")
        print(f"OK: wrote {MD_PATH.name} and README term lists ({len(tax['terms'])} terms)")
    elif mode == "check":
        stale = []
        if not MD_PATH.exists() or MD_PATH.read_text(encoding="utf-8") != md:
            stale.append("taxonomy.md")
        if README_PATH.read_text(encoding="utf-8") != readme_new:
            stale.append("README.md term lists")
        if stale:
            print(
                "ERROR: stale generated content: "
                + ", ".join(stale)
                + ". Run: python scripts/taxonomy_tools.py generate"
            )
            sys.exit(1)
        print(f"OK: {len(tax['terms'])} terms valid; JSON, CSV and Markdown in sync")
    else:
        print(f"Unknown mode '{mode}'. Use 'generate' or 'check'.")
        sys.exit(2)


if __name__ == "__main__":
    main()
